apiVersion: v1
kind: Service                   
metadata:
  name: nextjs-kube-service
spec:
  selector:
    app: next-landing-demo            
  ports:
  - port: 3000                 
    targetPort: 3000           
  type: NodePort
